language: python
python:
  - "3.6"
install:
  - pip install -U black pytest pytest-cov coveralls isort
  - python setup.py install
script:
  - python -m pytest --cov=pepsyn
  - ./format.sh check
after_success:
  - coveralls
