language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -U black pytest pytest-cov coveralls
  - python setup.py install
script:
  - python -m pytest --cov=pepsyn
  - black --check -v .
after_success:
  - coveralls
